server:
  port: ${PORT:8091}
spring:
  application:
    name: financieraoh-business

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://foh-eurekaserver.herokuapp.com/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

app:
  feign-client:
    core-service: https://foh-gateway.herokuapp.com/financieraoh-core/v1