server:
  port: 8099
spring:
  application:
    name: financieraoh-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka

zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    business:
      path: /financieraoh-business/v1/**
      service-id: FINANCIERAOH-BUSINESS
    core:
      path: /financieraoh-core/v1/**
      service-id: FINANCIERAOH-CORE