server:
  port: ${PORT:8092}
spring:
  application:
    name: financieraoh-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_POSTGRES_URI}/financieraoh
    username: ${DB_POSTGRES_USER}
    password: ${DB_POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://foh-eurekaserver.herokuapp.com/eureka/