server:
  port: ${PORT:8080}
spring:
  application:
    name: financieraoh-discovery-server

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
